### ISSUE TITLE
multiple EC_numbers with 3 characters on the last position are causing an error

### ISSUE THREAD

**Issue by gcremers** [enasequence/webin-cli#15] opened 2019-06-14 13:12 UTC
Hi,

I have been using webin-cli-1.8.4.jar, which works great so far except for one specific instance 
where the script is trying to parse something like  [ec:2.1.1.107,4.2.1.75].
> 2019-06-14T14:41:07 ERROR: Feature qualifier "EC_number" value "2.1.1.1074" is invalid. Refer to the feature documentation or ask a curator for guidance."

Other instances of multiple EC numbers, for instance [ec:2.7.1.11,2.7.1.90], are not a problem. 

However, when the fourth number consists of 3 characters (107 instead of 11) it gives out the above error message.

**Comment by raskoleinonen** [comment] 2019-06-14 13:22
Hi,

Could you please copy and paste here the /EC_number="XXX" qualifier from the flat file that is causing the problem?

Best & Thanks,
Rasko

**Comment by gcremers** [comment] 2019-06-14 13:42
Ah, I see now it is not creating one. The offending number is in the /product qualifier.

> FT                   /product="uroporphyrinogen III methyltransferase /
> FT                   synthase [ec:2.1.1.107,4.2.1.75]"

Having said that, an entry like:

> FT                   /product="cysteine desulfurase / selenocysteine lyase
> FT                   [ec:2.8.1.7,4.4.1.16]"

also does not have the  /EC_number qualifier, but is not seen as a problem.

Single numbers do have the  /EC_number qualifier.

**Comment by raskoleinonen** [comment] 2019-06-14 14:23
We may need to access the whole flat file entry to understand the exact problem. Perhaps you could upload your submission files including the manifest file to webin.ebi.ac.uk (FTP or Aspera) so that we can take a look?

**Comment by gcremers** [comment] 2019-06-17 07:35
I have uploaded two unzipped files(embl and fa) using the webin file uploader. I never can get FTP to work.

I have also added the manifest file and the report file.

The webin number is 44865.

**Comment by raskoleinonen** [comment] 2019-06-17 09:53
Thanks,

The problem is 4 digits (1074) in the 4th (last) position in the EC number:
2.1.1.1074

We checked the ExPASy (https://enzyme.expasy.org/) EC number dump:
ftp://ftp.expasy.org/databases/enzyme/enzyme.dat

and there are no EC numbers with four digits in the 4th place.

Like the ExPASy search interface we have a check that prevents using more than 3 digits in the 4th (last) position.

Best,
Rasko

**Comment by gcremers** [comment] 2019-06-17 12:26
Thanks for looking into this.

However,  in my Embl file there are no numbers that end with 4 digits in the last position (at least I have not been able to detect them).

Yet the validation fails because the validator thinks there is. The validator seems to add the 4th digit when there are 3 digits and a subsequent other number. It ignores the comma (or space or semicolon). I tried them as well.

Geert

**Comment by raskoleinonen** [comment] 2019-06-17 13:22
Ok, we have reproduced the error using manifest3B, 3B.fa.gz, mamc3b.embl.gz and are debugging Webin-CLI.

**Comment by raskoleinonen** [comment] 2019-06-17 13:39
A flat file parsing problem has been confirmed as you suggested in a previous comment:

```
FT                   /product="....
FT                   ...
FT                   [ec:3.5.1.108,4.2.1.59]"
```
3.5.1.1084 is being considered an EC number.

**Comment by raskoleinonen** [comment] 2019-06-17 13:59
EC numbers are extracted from the /product qualifier. This does not work correctly if more than once EC number is provided in the /product qualifier. Immediate fix is to remove EC numbers from /product qualifier before submission and add them using /EC_number qualifiers. We need to think a bit what is the best fix for the code.

**Comment by raskoleinonen** [comment] 2019-06-18 16:21
We plan to release a new Webin-CLI version that should fix the reported /product EC number parsing bug. This will happen late this week or late next week.

**Comment by gcremers** [comment] 2019-06-19 13:56
Superb. Thank you!

**Comment by raskoleinonen** [comment] 2019-06-20 15:58
There is a new version of Webin-CLI which should work correctly in the reported case:

https://github.com/enasequence/webin-cli/releases/tag/v1.8.6

**Comment by raskoleinonen** [comment] 2019-06-24 10:18
I am closing this ticket. Could you please create a new ticket if there is still a problem related to this.

**Closed by raskoleinonen** 2019-06-24 10:18 UTC
